import 'package:candidate_dashboard/core/core.dart';
import 'package:flutter/material.dart';

abstract final class AppColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.accentBlue,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.accentBlueLight,
    onPrimaryContainer: AppColors.accentBlue,
    secondary: AppColors.verdictGreen,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.verdictGreenLight,
    onSecondaryContainer: AppColors.verdictGreenDark,
    tertiary: AppColors.verdictOrange,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.verdictOrangeLight,
    onTertiaryContainer: AppColors.verdictOrangeDark,
    error: AppColors.dangerRed,
    onError: AppColors.white,
    errorContainer: AppColors.verdictRedLight,
    onErrorContainer: AppColors.verdictRedDark,
    surface: AppColors.white,
    onSurface: AppColors.slate900,
    onSurfaceVariant: AppColors.slate500,
    surfaceContainerLowest: AppColors.white,
    surfaceContainerLow: AppColors.iosGray,
    surfaceContainer: AppColors.white,
    surfaceContainerHigh: AppColors.slate100,
    surfaceContainerHighest: AppColors.slate100,
    outline: AppColors.slate300,
    outlineVariant: AppColors.slate200,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.slate900,
    onInverseSurface: AppColors.white,
    inversePrimary: AppColors.accentBlueDark,
    surfaceTint: AppColors.accentBlue,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.accentBlue,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.dark600,
    onPrimaryContainer: AppColors.accentBlueDark,
    secondary: AppColors.verdictGreen,
    onSecondary: AppColors.dark900,
    secondaryContainer: AppColors.verdictGreenSoft,
    onSecondaryContainer: AppColors.verdictGreenMod,
    tertiary: AppColors.verdictOrange,
    onTertiary: AppColors.dark900,
    tertiaryContainer: AppColors.verdictOrangeSoft,
    onTertiaryContainer: AppColors.verdictOrangeMod,
    error: AppColors.verdictRed,
    onError: AppColors.dark900,
    errorContainer: AppColors.verdictRedSoft,
    onErrorContainer: AppColors.verdictRedMod,
    surface: AppColors.dark700,
    onSurface: AppColors.darkText100,
    onSurfaceVariant: AppColors.darkText200,
    surfaceContainerLowest: AppColors.dark900,
    surfaceContainerLow: AppColors.dark900,
    surfaceContainer: AppColors.dark700,
    surfaceContainerHigh: AppColors.dark700,
    surfaceContainerHighest: AppColors.dark600,
    outline: AppColors.dark500,
    outlineVariant: AppColors.dark400,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.slate100,
    onInverseSurface: AppColors.slate900,
    inversePrimary: AppColors.accentBlue,
    surfaceTint: AppColors.accentBlue,
  );
}
